version: '3.8'

services:
  base-core-react:
    container_name:  react-mobx
    image: react-mobx
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
